[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
autoconfirm = false
disable_signup = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.external.github]
enabled = true
client_id = ""
secret = ""
redirect_uri = ""

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[jwt]
secret = "your-super-secret-jwt-token-with-at-least-32-characters-long"
exp = 3600

[functions]
[functions.docusign-auth]
verify_jwt = false 